
include "./dns.yar"
include "./http.yar"
include "./ssl.yar"
include "./irc.yar"
include "./smtp.yar"
include "./smb.yar"
include "./ssh.yar"
include "./dnp3.yar"
include "./darkcomet.yar"
include "./stratum.yar"
include "./njrat.yar"
include "./teamviewer.yar"
include "./vnc.yar"
include "./tftp.yar"

